[project]
authors = ["Pierre Poulain <pierre.poulain@cupnet.net>"]
channels = ["conda-forge", "bioconda", "nodefaults"]
description = "Pixi env for Jupyter Book"
name = "env-logiciels-bioinfo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
compile = "jupyter-book build cours"

[dependencies]
jupyter-book = "*"
